thebon/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from thebon import db
from thebon.forms import UserCreateForm, UserLoginForm
from thebon.models import User

import functools

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user = User(username=form.username.data,
                        password=generate_password_hash(form.password1.data),
                        email=form.email.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.')
    return render_template('auth/signup.html', form=form)

@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/login.html', form=form)

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        return view(**kwargs)
    return wrapped_view

thebon/views/crawling_views.py
from flask import Blueprint, render_template, g, request
from pandas.core.dtypes.missing import notnull
from thebon.models import User, User_data, Crawling
from thebon.views import myfunction
from thebon.views.auth_views import login_required
import sqlite3
import time
import pandas as pd

bp = Blueprint('crawling', __name__, url_prefix='/crawling')

@bp.route('/search/')
@login_required
def search_list():
    my_search_list = User_data.query.filter_by(user_id = g.user.id).all()
    return render_template('crawling/search_word.html', search_list=my_search_list)

# @bp.route('/crawling_list/')#크롤링 결과를 보여주는 화면
# @login_required
# def crawling_list(crawling_df):
#     # return render_template('crawling/crawling_list.html', crawling_df=crawling_df)
#     return render_template('test.html', crawling_df=crawling_df)

@bp.route('/sunup/<int:user_id>')
@login_required
def sunup(user_id):
    my_num = g.user.id
    my_search_list = User_data.query.order_by(User_data.search_word)
    return render_template('crawling/search_word.html', search_list=my_search_list)

@bp.route('/list/')
@login_required
def _list():
    my_crawling_list = Crawling.query.order_by(Crawling.create_date.desc())
    return render_template('crawling/crawling_list.html', crawling_list=my_crawling_list)

@bp.route('/detail/<int:crawling_id>/')
@login_required
def detail(crawling_id):
    crawling = Crawling.query.get_or_404(crawling_id)
    return render_template('crawling/crawling_detail.html', crawling=crawling)

@bp.route('/submit/')
@login_required
def submit():
    form = SubmitForm()
    return render_template('crawling/submit_form.html', form=form)

@bp.route('/updatedb/', methods=['POST','GET'])
@login_required
def updatedb():
    start = time.time()  # 시작 시간 저장
    # if request.method == 'POST':
    tmp_my_search_list = []
    data = request.form

    for i in data.items():  # items() method is used to return the list with all dictionary keys with values.
        tmp = i.__getitem__(1)
        tmp = tmp.strip()
        tmp_my_search_list.append(tmp)

    # 중복 검색어, 공백 검색어 제거
    my_search_list = list(dict.fromkeys(tmp_my_search_list))
    my_search_list = list(filter(None, my_search_list))
    print(my_search_list)

    # deleteRecord(g.user.id)
    updateRecord(g.user.id, my_search_list)
    print("time :", time.time() - start)  # 현재시각 - 시작시간 = 실행 시간
    return search_list()

@bp.route('/solo_search/', methods=['POST','GET'])
@login_required
def solo_search():
    start = time.time()  # 시작 시간 저장
    data = request.form
    search_word = request.form['solo_name']
    # result_df = myfunction.crawling_main_fun(search_word)
    large_dic = {}
    large_dic[search_word] = myfunction.crawling_main_fun(search_word)
    print("time :", time.time() - start)  # 현재시각 - 시작시간 = 실행 시간
    return render_template('crawling/crawling_list.html', large_dic=large_dic)
    # return render_template('crawling/crawling_list.html', crawling_df=result_df, search_word=search_word)

@bp.route('/multi_search/', methods=['POST','GET'])
@login_required
def multi_search():
    start = time.time()  # 시작 시간 저장
    tmp_my_search_list = []
    data = request.form
    result_df = pd.DataFrame

    for i in data.items():  # items() method is used to return the list with all dictionary keys with values.
        tmp = i.__getitem__(1)
        # tmp = tmp.strip()
        tmp_my_search_list.append(tmp)

    # 중복 검색어, 공백 검색어 제거
    my_search_list = list(dict.fromkeys(tmp_my_search_list))
    my_search_list = list(filter(None, my_search_list))
    print(my_search_list)

    #딕셔너리 이용하기
    large_dic = {}
    for search_word in my_search_list:
        large_dic[search_word] = myfunction.crawling_main_fun(search_word)
    print("time :", time.time() - start)  # 현재시각 - 시작시간 = 실행 시간
    return render_template('crawling/crawling_list.html', large_dic=large_dic)

def updateRecord(user_id, my_search_list):
    try:
        sqliteConnection = sqlite3.connect('thebon.db')
        cursor = sqliteConnection.cursor()
        print("Connected to SQLite for updateRecord")
        sql_delete_query = 'DELETE from User_data where user_id = '+str(user_id)
        cursor.execute(sql_delete_query)
        for searchword in my_search_list:
            searchword = "'" + searchword + "'"
            sql_insert_query = 'insert into User_data(user_id, search_word) values(' + '1' + ', ' + searchword + ')'
            print(sql_insert_query)
            cursor.execute(sql_insert_query)
        sqliteConnection.commit()
        print("Record updated successfully ")
        cursor.close()
    except sqlite3.Error as error:
        print("Failed to delete record from sqlite table", error)
    finally:
        if sqliteConnection:
            sqliteConnection.close()
            print("the sqlite connection is closed")


# @bp.route('/more_info/')
# @login_required
# def more_info():
#     print("aaaaaaaaaaaaaaaaa")
#     if request.method == 'GET':
#         tmp_my_search_list = []
#         data = request.form
#         print(data)

@bp.route('/more_info/', methods=['POST','GET'])
@login_required
def more_info():
    start = time.time()  # 시작 시간 저장
    target_url = request.form['art_url']
    print(target_url)
    print("time spent : ", time.time() - start)  # 현재시각 - 시작시간 = 실행 시간
    sum_origin, sum_trans = myfunction.more_info(target_url)
    return render_template('crawling/sum_popup.html', sum_origin=sum_origin, sum_trans=sum_trans)
    

thebon/templates/!test.html
{% extends 'base.html' %}
{% block content %}

<main id="main">
    <div class="container" border>
        <div class="row section featured topspace">
            {% for key, value in large_dic.items()%}
            <h2 class="section-title"><span>
                    <p style="font-size:50%">{{ key }} 검색 결과는 {{value.shape[0]}}개입니다</p> 
                </span></h2>
            <ul>
                {% for index, row in value.iterrows() %}
                <div class="row">
                    <table style="border-collapse: collapse; width: 65%; height: 110px;" border="0"
                        class="mce-item-table" data-mce-style="border-collapse: collapse; width: 65%; height: 110px;">
                        <tr>
                            <td style="width: 30%;">
                                <div>
                                    <span style="font-style: italic ;"><a href="{{row.link}}" target='_blank'>{{
                                            row.title }}</a></span>
                                </div>
                            </td>

                            <td style="width: 20%;" rowspan="3">
                                <!-- <button type="button" class="btn btn-primary" style="width: 70%;"
                                    onclick="window.open('http://webtong.kr','Summary','width=830,height=600,location=no,status=no,scrollbars=yes');">Summary</button> -->

                                    
                                <button type="button" class="btn btn-primary" style="width: 70%;"
                                    onclick="window.open('{{ url_for('crawling.more_info')}}','Summary','width=830,height=600,location=no,status=no,scrollbars=yes');">Summary</button>

                                <p id="Summary"></p>
                            </td>
                        </tr>
                        <tr>
                            <td style="width: 80%;">
                                <div>{{ row.snippet_tran }}</div>
                            </td>
                        </tr>
                        <tr>
                            <td style="width: 80%;">
                                <div>{{ row.snippet }}
                                </div>
                            </td>
                        </tr>
                    </table>
                </div>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
</main>

{% endblock %}

thebon/templates/!test2 - 복사본.html
{% extends 'base.html' %}
{% block content %}

<main id="main">
    <div class="container" border>
        <div class="row section featured topspace">
            {% for key, value in large_dic.items()%}
            <h2 class="section-title"><span>
                    <p style="font-size:50%">{{ key }} 검색 결과는 {{value.shape[0]}}개입니다</p> 
                </span></h2>
            <ul>
                {% for index, row in value.iterrows() %}
                <div class="row">
                    <table style="border-collapse: collapse; width: 65%; height: 110px;" border="0"
                        class="mce-item-table" data-mce-style="border-collapse: collapse; width: 65%; height: 110px;">
                        <tr>
                            <td style="width: 30%;">
                                <div>
                                    <span style="font-style: italic ;"><a href="{{row.link}}" target='_blank'>{{
                                            row.title }}</a></span>
                                </div>
                            </td>

                            <td style="width: 20%;" rowspan="3">
                                <!-- <button type="button" class="btn btn-primary" style="width: 70%;"
                                    onclick="window.open('http://webtong.kr','Summary','width=830,height=600,location=no,status=no,scrollbars=yes');">Summary</button> -->

                                    
                                <button type="button" class="btn btn-primary" style="width: 70%;"
                                    onclick="window.open('{{ url_for('crawling.more_info')}}','Summary','width=830,height=600,location=no,status=no,scrollbars=yes');">Summary</button>

                                <p id="Summary"></p>
                            </td>
                        </tr>
                        <tr>
                            <td style="width: 80%;">
                                <div>{{ row.snippet_tran }}</div>
                            </td>
                        </tr>
                        <tr>
                            <td style="width: 80%;">
                                <div>{{ row.snippet }}
                                </div>
                            </td>
                        </tr>
                    </table>
                </div>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
</main>

{% endblock %}

thebon/templates/!test2.html
{% extends 'base.html' %}
{% block content %}

<main id="main">
    <div class="container" border>
        <div class="row section featured topspace">
            {% for key, value in large_dic.items()%}
            <h2 class="section-title"><span>
                    <p style="font-size:50%">{{ key }} 검색 결과는 {{value.shape[0]}}개입니다</p> 
                </span></h2>
            <ul>
                {% for index, row in value.iterrows() %}
                <div class="row">
                    <table style="border-collapse: collapse; width: 65%; height: 110px;" border="0"
                        class="mce-item-table" data-mce-style="border-collapse: collapse; width: 65%; height: 110px;">
                        <tr>
                            <td style="width: 30%;">
                                <div>
                                    <span style="font-style: italic ;"><a href="{{row.link}}" target='_blank'>{{
                                            row.title }}</a></span>
                                </div>
                            </td>

                            <td style="width: 20%;" rowspan="3">
                                <!-- <button type="button" class="btn btn-primary" style="width: 70%;"
                                    onclick="window.open('http://webtong.kr','Summary','width=830,height=600,location=no,status=no,scrollbars=yes');">Summary</button> -->

                                    
                                <button type="button" class="btn btn-primary" style="width: 70%;"
                                    onclick="window.open('{{ url_for('crawling.more_info')}}','Summary','width=830,height=600,location=no,status=no,scrollbars=yes');">Summary</button>

                                <p id="Summary"></p>
                            </td>
                        </tr>
                        <tr>
                            <td style="width: 80%;">
                                <div>{{ row.snippet_tran }}</div>
                            </td>
                        </tr>
                        <tr>
                            <td style="width: 80%;">
                                <div>{{ row.snippet }}
                                </div>
                            </td>
                        </tr>
                    </table>
                </div>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
</main>

{% endblock %}

thebon/templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    
    <title>더본솔루션</title>

    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.1.3/darkly/bootstrap.min.css"> -->

    <style>
    .container { margin: 100px auto; }
    h1 { margin-bottom: 20px; }
    </style>

</head>
<body>
{% include "navbar.html" %}

<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

<!-- jQuery JS -->
<script src="{{ url_for('static', filename='jquery-3.6.0.min.js') }}"></script>
<!-- Bootstrap JS -->
<script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>

{% block script %}<!-- 자바스크립트 Start -->

<script src="https://code.jquery.com/jquery-1.12.4.min.js"
        integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ"
        crossorigin="anonymous"></script>
<script type="text/javascript" src="../../static/dynamic-form.js"></script>

{% endblock %} <!-- 자바스크립트 End -->

</body>

<!--&lt;!&ndash;jQuery Dynamic&ndash;&gt;-->
<!--<script type="text/javascript">-->

<!--  var _gaq = _gaq || [];-->
<!--  _gaq.push(['_setAccount', 'UA-36251023-1']);-->
<!--  _gaq.push(['_setDomainName', 'jqueryscript.net']);-->
<!--  _gaq.push(['_trackPageview']);-->

<!--  (function() {-->
<!--    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;-->
<!--    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';-->
<!--    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);-->
<!--  })();-->
<!--</script>-->

</html>

thebon/templates/form_errors.html
<!-- 필드오류 -->
{% for field, errors in form.errors.items() %}
<div class="alert alert-danger" role="alert">
    <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
</div>
{% endfor %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

thebon/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport"    content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author"      content="Sergey Pozhilov (GetTemplate.com)">
	
	<title>Initio - Free, multipurpose html5 template by GetTemplate</title>

	<link rel="shortcut icon" href="assets/images/gt_favicon.png">
	
	<!-- Bootstrap -->
	<link href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.no-icons.min.css" rel="stylesheet">
	<!-- Icons -->
	<link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
	<!-- Fonts -->
	<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Alice|Open+Sans:400,300,700">
	<!-- Custom styles -->
	<link rel="stylesheet" href="assets/css/styles.css">

	<!--[if lt IE 9]> <script src="assets/js/html5shiv.js"></script> <![endif]-->
</head>
<body class="home">

<header id="header">
	<div id="head" class="parallax" parallax-speed="2">
		<h1 id="logo" class="text-center">
			<img class="img-circle" src="assets/images/guy.jpg" alt="">
			<span class="title">Anthony Russel</span>
			<span class="tagline">A mystery person<br>
				<a href="">anthony.russel42@example.com</a></span>
		</h1>
	</div>

	<nav class="navbar navbar-default navbar-sticky">
		<div class="container-fluid">
			
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
			</div>
			
			<div class="navbar-collapse collapse">
				
				<ul class="nav navbar-nav">
					<li class="active"><a href="index.html">Home</a></li>
					<li><a href="about.html">About</a></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">More Pages <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="sidebar-left.html">Left Sidebar</a></li>
							<li><a href="sidebar-right.html">Right Sidebar</a></li>
							<li><a href="single.html">Blog Post</a></li>
						</ul>
					</li>
					<li><a href="blog.html">Blog</a></li>
				</ul>
			
			</div><!--/.nav-collapse -->			
		</div>	
	</nav>
</header>

<main id="main">

	<div class="container">
		
		<div class="row section topspace">
			<div class="col-md-12">
				<p class="lead text-center text-muted">Let me tell you something my friend. hope is a dangerous thing. hope can drive a man insane. you <a href="about.html">measure</a> yourself by the people who measure themselves by you. it only took me <a href="sidebar-right.html">six days</a>. </p>
			</div>
		</div> <!-- / section -->
		
		<div class="row section featured topspace">
			<h2 class="section-title"><span>Services</span></h2>
			<div class="row">
				<div class="col-sm-6 col-md-3">
					<h3 class="text-center">Custom website design</h3>
					<p>I don't think they tried to market it to the billionaire, spelunking, base-jumping crowd. i did the same thing to gandhi, he didn't eat for three weeks. i once heard a wise man say there are no perfect men.</p>
					<p class="text-center"><a href="" class="btn btn-action">Read more</a></p>
				</div>
				<div class="col-sm-6 col-md-3">
					<h3 class="text-center">Wordpress integration</h3>
					<p>I don't think they tried to market it to the billionaire, spelunking, base-jumping crowd. i did the same thing to gandhi, he didn't eat for three weeks. i once heard a wise man say there are no perfect men.</p>
					<p class="text-center"><a href="" class="btn btn-action">Read more</a></p>
				</div>
				<div class="col-sm-6 col-md-3">
					<h3 class="text-center">Application development</h3>
					<p>I don't think they tried to market it to the billionaire, spelunking, base-jumping crowd. i did the same thing to gandhi, he didn't eat for three weeks. i once heard a wise man say there are no perfect men.</p>
					<p class="text-center"><a href="" class="btn btn-action">Read more</a></p>
				</div>
				<div class="col-sm-6 col-md-3">
					<h3 class="text-center">SEO &amp; SEM services</h3>
					<p>I don't think they tried to market it to the billionaire, spelunking, base-jumping crowd. i did the same thing to gandhi, he didn't eat for three weeks. i once heard a wise man say there are no perfect men.</p>
					<p class="text-center"><a href="" class="btn btn-action">Read more</a></p>
				</div>
			</div>
		</div> <!-- / section -->
	
		<div class="row section recentworks topspace">
			
			<h2 class="section-title"><span>Recent Works</span></h2>
			
			<div class="thumbnails recentworks row">
				
				<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
					<a class="thumbnail" href="sidebar-right.html">
						<span class="img">
							<img src="assets/images/s1.jpg" alt="">
							<span class="cover"><span class="more">See details &rarr;</span></span>
						</span>
						<span class="title">Sample title - big data solutions</span>
					</a>
					<span class="details"><a href="">Web design</a> | <a href="">Wordpress</a> | <a href="">Logotype</a></span>
					<h4></h4>
					<p></p>
				</div>
				
				<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
					<a class="thumbnail" href="sidebar-right.html">
						<span class="img">
							<img src="assets/images/s1.jpg" alt="">
							<span class="cover"><span class="more">See details &rarr;</span></span>
						</span>
						<span class="title">Pure ipsum - development services for people</span>
					</a>
					<span class="details"><a href="">Web design</a> | <a href="">Wordpress</a></span>
					<h4></h4>
					<p></p>
				</div>
				
				<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
					<a class="thumbnail" href="sidebar-right.html">
						<span class="img">
							<img src="assets/images/s1.jpg" alt="">
							<span class="cover"><span class="more">See details &rarr;</span></span>
						</span>
						<span class="title">Lorem studios - interior and patio design</span>
					</a>
					<span class="details"><a href="">Web design</a> | <a href="">Logotype</a></span>
					<h4></h4>
					<p></p>
				</div>

				<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
					<a class="thumbnail" href="sidebar-right.html">
						<span class="img">
							<img src="assets/images/s1.jpg" alt="">
							<span class="cover"><span class="more">See details &rarr;</span></span>
						</span>
						<span class="title">Pure ipsum - development services for people</span>
					</a>
					<span class="details"><a href="">Web design</a> | <a href="">Wordpress</a></span>
					<h4></h4>
					<p></p>
				</div>
				
				<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
					<a class="thumbnail" href="sidebar-right.html">
						<span class="img">
							<img src="assets/images/s1.jpg" alt="">
							<span class="cover"><span class="more">See details &rarr;</span></span>
						</span>
						<span class="title">Lorem studios - interior and patio design</span>
					</a>
					<span class="details"><a href="">Web design</a> | <a href="">Logotype</a></span>
					<h4></h4>
					<p></p>
				</div>

				<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
					<a class="thumbnail" href="sidebar-right.html">
						<span class="img">
							<img src="assets/images/s1.jpg" alt="">
							<span class="cover"><span class="more">See details &rarr;</span></span>
						</span>
						<span class="title">Lorem studios - interior and patio design</span>
					</a>
					<span class="details"><a href="">Web design</a> | <a href="">Logotype</a></span>
					<h4></h4>
					<p></p>
				</div>
			</div>

		</div> <!-- /section -->

		<div class="row section topspace">
			<div class="panel panel-cta"><div class="panel-body">
				<div class="col-lg-8">
					<p>A simple, nice-looking <b>call to action box</b>. Boxing is about respect. getting it for yourself, 
					and taking it away from the other guy. no, this is mount everest. </p>
				</div>
				<div class="col-lg-4 text-right">
					<a href="http://www.gettemplate.com/downloads/initio.zip " class="btn btn-primary btn-lg">Download template</a>
				</div>
			</div></div>
		</div> <!-- /section -->

		<div class="row section clients topspace">
			<h2 class="section-title"><span>Clients</span></h2>
			<div class="col-lg-12">
				<p>
					<img src="assets/images/sample_clients.png" alt="">
				</p>
			</div>
		</div> <!-- /section -->

	</div>	<!-- /container -->

</main>

<footer id="footer">
	<div class="container">
		<div class="row">
			<div class="col-md-3 widget">
				<h3 class="widget-title">Contact</h3>
				<div class="widget-body">
					<p>+234 23 9873237<br>
						<a href="mailto:#">some.email@somewhere.com</a><br>
						<br>
						234 Hidden Pond Road, Ashland City, TN 37015
					</p>	
				</div>
			</div>

			<div class="col-md-3 widget">
				<h3 class="widget-title">Follow me</h3>
				<div class="widget-body">
					<p class="follow-me-icons">
						<a href=""><i class="fa fa-twitter fa-2"></i></a>
						<a href=""><i class="fa fa-dribbble fa-2"></i></a>
						<a href=""><i class="fa fa-github fa-2"></i></a>
						<a href=""><i class="fa fa-facebook fa-2"></i></a>
					</p>
				</div>
			</div>

			<div class="col-md-3 widget">
				<h3 class="widget-title">Text widget</h3>
				<div class="widget-body">
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque, nihil natus explicabo ipsum quia iste aliquid repellat eveniet velit ipsa sunt libero sed aperiam id soluta officia asperiores adipisci maxime!</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque, nihil natus explicabo ipsum quia iste aliquid repellat eveniet velit ipsa sunt libero sed aperiam id soluta officia asperiores adipisci maxime!</p>
				</div>
			</div>

			<div class="col-md-3 widget">
				<h3 class="widget-title">Form widget</h3>
				<div class="widget-body">
					<p>+234 23 9873237<br>
						<a href="mailto:#">some.email@somewhere.com</a><br>
						<br>
						234 Hidden Pond Road, Ashland City, TN 37015
					</p>	
				</div>
			</div>

		</div> <!-- /row of widgets -->
	</div>
</footer>

<footer id="underfooter">
	<div class="container">
		<div class="row">
			
			<div class="col-md-6 widget">
				<div class="widget-body">
					<p>234 Hidden Pond Road, Ashland City, TN 37015 </p>
				</div>
			</div>

			<div class="col-md-6 widget">
				<div class="widget-body">
					<p class="text-right">
						Copyright &copy; 2014, Your awesome name here<br> 
						Design: <a href="http://www.gettemplate.com" rel="designer">Initio by GetTemplate</a> </p>
				</div>
			</div>

		</div> <!-- /row of widgets -->
	</div>
</footer>



<!-- JavaScript libs are placed at the end of the document so the pages load faster -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="assets/js/template.js"></script>
</body>
</html>

thebon/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Thebon</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        {% if g.user %}
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('auth.logout') }}">{{ g.user.username }} (로그아웃)</a>
            </li>
        </ul>
        {% else %}
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('auth.signup') }}">회원가입</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
            </li>
        </ul>
        {% endif %}
    </div>
</nav>

thebon/templates/temp.html
<!DOCTYPE html>
<html>



<body id="tinymce" class="mce-content-body " data-id="content" contenteditable="true" spellcheck="false">
    <p><br data-mce-bogus="1"></p>

    <h1>여기는 제목 1</h1>
    <p>여기에 텍스트를 입력합니다.</p>
    <hr>
    
    
    
        <h2 class="section-title"><span>
                <p style="font-size:50%">Samsung Sdi</p>
            </span></h2>
        <p>검색결과가 없습니다ㅠ</p>

</body>

</html>