thebon/views/crawling_views.py
from flask import Blueprint, render_template, g, request
from pandas.core.dtypes.missing import notnull
from thebon.models import User, User_data, Crawling
from thebon.views import myfunction
from thebon.views.auth_views import login_required
import sqlite3
import time
import pandas as pd

bp = Blueprint('crawling', __name__, url_prefix='/crawling')

@bp.route('/search/')
@login_required
def search_list():
    my_search_list = User_data.query.filter_by(user_id = g.user.id).all()
    return render_template('crawling/search_word.html', search_list=my_search_list)

# @bp.route('/crawling_list/')#크롤링 결과를 보여주는 화면
# @login_required
# def crawling_list(crawling_df):
#     # return render_template('crawling/crawling_list.html', crawling_df=crawling_df)
#     return render_template('test.html', crawling_df=crawling_df)

@bp.route('/sunup/<int:user_id>')
@login_required
def sunup(user_id):
    my_num = g.user.id
    my_search_list = User_data.query.order_by(User_data.search_word)
    return render_template('crawling/search_word.html', search_list=my_search_list)

@bp.route('/list/')
@login_required
def _list():
    my_crawling_list = Crawling.query.order_by(Crawling.create_date.desc())
    return render_template('crawling/crawling_list.html', crawling_list=my_crawling_list)

@bp.route('/detail/<int:crawling_id>/')
@login_required
def detail(crawling_id):
    crawling = Crawling.query.get_or_404(crawling_id)
    return render_template('crawling/crawling_detail.html', crawling=crawling)

@bp.route('/submit/')
@login_required
def submit():
    form = SubmitForm()
    return render_template('crawling/submit_form.html', form=form)

@bp.route('/updatedb/', methods=['POST','GET'])
@login_required
def updatedb():
    start = time.time()  # 시작 시간 저장
    # if request.method == 'POST':
    tmp_my_search_list = []
    data = request.form

    for i in data.items():  # items() method is used to return the list with all dictionary keys with values.
        tmp = i.__getitem__(1)
        tmp = tmp.strip()
        tmp_my_search_list.append(tmp)

    # 중복 검색어, 공백 검색어 제거
    my_search_list = list(dict.fromkeys(tmp_my_search_list))
    my_search_list = list(filter(None, my_search_list))
    print(my_search_list)

    # deleteRecord(g.user.id)
    updateRecord(g.user.id, my_search_list)
    print("time :", time.time() - start)  # 현재시각 - 시작시간 = 실행 시간
    return search_list()

@bp.route('/solo_search/', methods=['POST','GET'])
@login_required
def solo_search():
    start = time.time()  # 시작 시간 저장
    data = request.form
    search_word = request.form['solo_name']
    # result_df = myfunction.crawling_main_fun(search_word)
    large_dic = {}
    large_dic[search_word] = myfunction.crawling_main_fun(search_word)
    print("time :", time.time() - start)  # 현재시각 - 시작시간 = 실행 시간
    return render_template('crawling/crawling_list.html', large_dic=large_dic)
    # return render_template('crawling/crawling_list.html', crawling_df=result_df, search_word=search_word)

@bp.route('/multi_search/', methods=['POST','GET'])
@login_required
def multi_search():
    start = time.time()  # 시작 시간 저장
    tmp_my_search_list = []
    data = request.form
    result_df = pd.DataFrame

    for i in data.items():  # items() method is used to return the list with all dictionary keys with values.
        tmp = i.__getitem__(1)
        # tmp = tmp.strip()
        tmp_my_search_list.append(tmp)

    # 중복 검색어, 공백 검색어 제거
    my_search_list = list(dict.fromkeys(tmp_my_search_list))
    my_search_list = list(filter(None, my_search_list))
    print(my_search_list)

    #딕셔너리 이용하기
    large_dic = {}
    for search_word in my_search_list:
        large_dic[search_word] = myfunction.crawling_main_fun(search_word)
    print("time :", time.time() - start)  # 현재시각 - 시작시간 = 실행 시간
    return render_template('crawling/crawling_list.html', large_dic=large_dic)

def updateRecord(user_id, my_search_list):
    try:
        sqliteConnection = sqlite3.connect('thebon.db')
        cursor = sqliteConnection.cursor()
        print("Connected to SQLite for updateRecord")
        sql_delete_query = 'DELETE from User_data where user_id = '+str(user_id)
        cursor.execute(sql_delete_query)
        for searchword in my_search_list:
            searchword = "'" + searchword + "'"
            sql_insert_query = 'insert into User_data(user_id, search_word) values(' + '1' + ', ' + searchword + ')'
            print(sql_insert_query)
            cursor.execute(sql_insert_query)
        sqliteConnection.commit()
        print("Record updated successfully ")
        cursor.close()
    except sqlite3.Error as error:
        print("Failed to delete record from sqlite table", error)
    finally:
        if sqliteConnection:
            sqliteConnection.close()
            print("the sqlite connection is closed")


# @bp.route('/more_info/')
# @login_required
# def more_info():
#     print("aaaaaaaaaaaaaaaaa")
#     if request.method == 'GET':
#         tmp_my_search_list = []
#         data = request.form
#         print(data)

@bp.route('/more_info/', methods=['POST','GET'])
@login_required
def more_info():
    start = time.time()  # 시작 시간 저장
    target_url = request.form['art_url']
    print(target_url)
    print("time spent : ", time.time() - start)  # 현재시각 - 시작시간 = 실행 시간
    sum_origin, sum_trans = myfunction.more_info(target_url)
    return render_template('crawling/sum_popup.html', sum_origin=sum_origin, sum_trans=sum_trans)
    

thebon/templates/crawling/crawling_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>{{  crawling.title }}</h1>

<div>
    {{  crawling.snippet }}
</div>
{% endblock %}

thebon/templates/crawling/crawling_list.html
{% if crawling_list %}
    <ul>
    {% for i in crawling_list %}
        <li><a href="/detail/{{ i.id }}/">{{ i.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>질문이 없습니다.</p>
{% endif %}

thebon/templates/crawling/dynamic-form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>jQuery Dynamic Forms Plugin Example</title>
    <link href="https://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.1.3/darkly/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
    <script type="text/javascript" src="js/dynamic-form.js"></script>
    <style>

    .container { margin: 150px auto; }
    h1 { margin-bottom: 50px; }
  </style>
</head>
<body><div id="jquery-script-menu">
<div class="jquery-script-center">
<ul>
<li><a href="https://www.jqueryscript.net/form/dynamic-forms-fields.html">Download This Plugin</a></li>
<li><a href="https://www.jqueryscript.net/">Back To jQueryScript.Net</a></li>
</ul>
<div class="jquery-script-ads"><script type="text/javascript"><!--
google_ad_client = "ca-pub-2783044520727903";
/* jQuery_demo */
google_ad_slot = "2780937993";
google_ad_width = 728;
google_ad_height = 90;
//-->
</script>
<script type="text/javascript"
src="https://pagead2.googlesyndication.com/pagead/show_ads.js">
</script></div>
<div class="jquery-script-clear"></div>
</div>
</div>
    <div class="container">
        <h1>jQuery Dynamic Forms Plugin Example</h1>
        <form method="POST">
	        <div class="form-group" id="dynamic_form">
                <div class="row">
	                <div class="col-md-3">
	                    <input type="text" name="p_name" id="p_name" placeholder="Enter Product Name" class="form-control">
	                </div>
	                <div class="col-md-3">
	                    <input type="text" class="form-control" name="quantity" id="quantity" placeholder="Enter Product Quantity" onkeyup = "if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')";>
	                </div>
	                <div class="col-md-4">
	                    <textarea class="form-control" rows="1" name="remarks" placeholder="Enter Remarks" id="remarks"></textarea>
	                </div>
	                <div class="button-group">
	                    <a href="javascript:void(0)" class="btn btn-primary" id="plus5">Add More</a>
	                    <a href="javascript:void(0)" class="btn btn-danger" id="minus5">Remove</a>
	                </div>
	            </div>
            </div>
			<button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
    <script>
        $(document).ready(function() {
        	var dynamic_form =  $("#dynamic_form").dynamicForm("#dynamic_form","#plus5", "#minus5", {
		        limit:10,
		        formPrefix : "dynamic_form",
		        normalizeFullForm : false
		    });

        	dynamic_form.inject([{p_name: 'Hemant',quantity: '123',remarks: 'testing remark'},{p_name: 'Harshal',quantity: '123',remarks: 'testing remark'}]);

		    $("#dynamic_form #minus5").on('click', function(){
		    	var initDynamicId = $(this).closest('#dynamic_form').parent().find("[id^='dynamic_form']").length;
		    	if (initDynamicId === 2) {
		    		$(this).closest('#dynamic_form').next().find('#minus5').hide();
		    	}
		    	$(this).closest('#dynamic_form').remove();
		    });

		    $('form').on('submit', function(event){
	        	var values = {};
				$.each($('form').serializeArray(), function(i, field) {
				    values[field.name] = field.value;
				});
				console.log(values)
        		event.preventDefault();
        	})
        });
    </script>
</body><script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-36251023-1']);
  _gaq.push(['_setDomainName', 'jqueryscript.net']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</html>

thebon/templates/crawling/myformtest.html
{% extends 'base.html' %}
{% block content %}

<form name="loginForm" action="{{ url_for('crawling.save') }}" method="POST">
    계정 : <input type="text" name="userId"><br>
    비밀번호 : <input type="password" name="password"><br>
    <input type="hidden" name="loginType" value="admin">
    <input type="button" onclick="login()" value="로그인">
</form>

<script type="text/javascript">
        function login(){
            var loginForm = document.loginForm;
            var userId = loginForm.userId.value;
            var password = loginForm.password.value;

            if(!userId || !password){
                alert("아이디와 비밀번호를 모두 입력해주세요.")
            }else{
                loginForm.submit();
            }
        }
</script>

thebon/templates/crawling/search_word - 복사본 JScript.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <form action="{{ url_for('crawling.save') }}" method="POST">
        <div class="form-group" id="dynamic_form">
            <div class="row">
                <div class="col-md-5">
                        <input type="text" name="p_name" id="p_name" placeholder="Enter Keyword" class="form-control">
<!--                    <input type="text" name="p_name">-->
                </div>
                <div class="button-group">
                    <a href="javascript:void(0)" class="btn btn-primary" id="plus5">Add More</a>
                    <a href="javascript:void(0)" class="btn btn-danger" id="minus5">Remove</a>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12 text-center">
                <br/>
                <button class="btn btn-info btn-md" type="submit">Add Project</button>
                <button class="btn btn-danger btn-md" type="reset">Cancel</button>
            </div>
        </div>
    </form>
</div>

<!-- jQuery JS -->
<script src="{{ url_for('static', filename='jquery-3.6.0.min.js') }}"></script>

<script>
        $(document).ready(function() {
        	var dynamic_form =  $("#dynamic_form").dynamicForm("#dynamic_form","#plus5", "#minus5", {
		        limit:10,
		        formPrefix : "dynamic_form",
		        normalizeFullForm : false
		    });

        	dynamic_form.inject([

        	    {p_name: '1111111'},
        	    {p_name: 'Karshal'},
        	    {p_name: 'suggnup'}
<!--                {% if search_list %}-->
<!--                    {% for i in search_list %}-->
<!--        	            {p_name: '{{i.search_word}}'},-->
<!--            	    {% endfor %}-->
<!--            	{% endif %}-->

        	    ]);


		    $("#dynamic_form #minus5").on('click', function(){
		    	var initDynamicId = $(this).closest('#dynamic_form').parent().find("[id^='dynamic_form']").length;
		    	if (initDynamicId === 2) {
		    		$(this).closest('#dynamic_form').next().find('#minus5').hide();
		    	}
		    	$(this).closest('#dynamic_form').remove();
		    });

		    $('form').on('submit', function(event){
	        	var values = {};
				$.each($('form').serializeArray(), function(i, field) {
				    values[field.name] = field.value;
				});
				console.log(values)
        		event.preventDefault();
        	})
        });
</script>
{% endblock %}

thebon/templates/crawling/search_word - 복사본.html
{% extends 'base.html' %}
{% block content %}

{% if search_list %}
{% for i in search_list %}
<div class="row">
    <div class="col-md-5">
        <input type="text" name="p_name" id="p_name" placeholder="{{i.search_word }}" class="form-control">
    </div>
</div>

{% endfor %}
<button type="submit" class="btn btn-primary">모두 검색하기</button>
{% else %}
<p>등록된 검색어가 없습니다.</p>
{% endif %}

{% endblock %}

thebon/templates/crawling/search_word.html
{% extends 'base.html' %}
{% block content %}

<script type="text/javascript">
        function SaveWord(index){
            if (index == 1) {            
                document.submitForm.action="{{ url_for('crawling.updatedb') }}";
                }
            if (index == 2) {
                document.submitForm.action="{{ url_for('crawling.multi_search') }}";
                }
            document.submitForm.submit();
        }
        
        function SoloSearch(){
            if ($('#solo_name').val().trim() != '') {                
                document.soloform.action="{{ url_for('crawling.solo_search') }}";
                document.soloform.submit();
                }
            else {
                alert("검색어를 입력해 주세요")
                $('#solo_name').focus();
                }
        }
</script>

<div class="container" style="
    margin-left: 128px;
    margin-top: 42px;
    margin-bottom: 48px;">
    <form name="soloform" action="{{ url_for('crawling.updatedb') }}" method="POST">
        <div class="form-solo" id="form-solo">
            <div class="row">
                <div class="col-md-5">
                    <input type="text" name="solo_name" id="solo_name" placeholder="Enter Keyword" class="form-control">
                </div>
                <button type="submit" class="btn btn-outline-info" onclick="SoloSearch()">Search</button>
            </div>
        </div>
    </form>
</div>

<div class="container" style="
    margin-left: 128px;
    margin-top: 53px;
    margin-right: 0px;
    margin-bottom: 15px;
">
<!--    <form name="submitForm" action="{{ url_for('crawling.updatedb') }}" method="POST">-->
    <form name="submitForm" method="POST">
        <div class="form-group" id="dynamic_form">
            <div class="row">
                <div class="col-md-5">
                    <input type="text" name="p_name" id="p_name" placeholder="Enter Keyword" class="form-control">
                </div>
                <div class="button-group">
                    <a href="javascript:void(0)" class="btn btn-primary" id="plus5">Add More</a>
                    <a href="javascript:void(0)" class="btn btn-danger" id="minus5">Remove</a>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-outline-success" onclick="SaveWord(1)">Save</button>
        <button type="submit" class="btn btn-outline-info" onclick="SaveWord(2)">Search</button>
    </form>
</div>

<!-- jQuery JS -->
<script src="{{ url_for('static', filename='jquery-3.6.0.min.js') }}"></script>

<script>
        $(document).ready(function() {
        	var dynamic_form =  $("#dynamic_form").dynamicForm("#dynamic_form","#plus5", "#minus5", {
		        limit:1024,
		        formPrefix : "dynamic_form",
		        normalizeFullForm : false
		    });

        	dynamic_form.inject([
                {% if search_list %}
                    {% for i in search_list %}
        	            {p_name: '{{i.search_word}}'},
            	    {% endfor %}
// <!--            	    {p_name: '  '},-->
            	{% endif %}
        	    ]);

		    $("#dynamic_form #minus5").on('click', function(){

		        // alert ("minus5  ")
		    	var initDynamicId = $(this).closest('#dynamic_form').parent().find("[id^='dynamic_form']").length;
		    	if (initDynamicId === 2) {
		    		$(this).closest('#dynamic_form').next().find('#minus5').hide();
		    	}
		    	$(this).closest('#dynamic_form').remove();
		    });

		    $('form').on('submit', function(event){
	        	var values = {};
				$.each($('form').serializeArray(), function(i, field) {
				    values[field.name] = field.value;
				});
				console.log(values)
        		event.preventDefault();
        	})


        	$("#dynamic_form #search5").on('click', function(){
                alert ("dynamic_form You clicked")
            })


            $(".form-button").click(function () {
                alert ("You clicked")
            })
});

</script>

{% endblock %}

thebon/templates/crawling/sum_popup.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>

<body>

    <div class="container" style="
    margin-left: 30px;
    margin-top: 30px;
    margin-right: 30px;
    margin-bottom: 30px;
">

        <tr>
            <td style="width: 80%;">
                <div>{{ sum_trans }}</div>
            </td>
        </tr>
        <br>
        <tr>
            <td style="width: 80%;">
                <div>{{ sum_origin }}
                </div>
            </td>
        </tr>

    </div>
</body>

</html>